# Site settings
title: RIDI Corporation
header-img: img/home-bg.jpg
email: start@ridi.com
description: "RIDI Corporation"
url: "http://www.ridicorp.com"
baseurl: ""

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: pretty

gems:
  - jekyll-paginate
  - jekyll-gravatar

paginate: 5
paginate_path: "/blog/page:num/"

exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "config.ru", "Gemfile", "Gemfile.lock"]
