# Site settings
title: RIDI Corporation
header-img: img/home-bg.jpg
email: start@ridi.com
description: "RIDI Corporation"
url: "http://www.ridicorp.com"
baseurl: ""

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 10
paginate_path: "articles/page:num/"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "config.ru", "Gemfile", "Gemfile.lock", "vendor", "Procfile", "Rakefile"]
