department: 제휴 부문
head: 제휴 부문
jobs:
  - title: 장르소설 제휴 담당자 (신입 혹은 경력)
    description:
      - 장르소설(로맨스, 판타지무협, 로맨스판타지) 출판사와의 커뮤니케이션, 웹소설 콘텐츠 소싱
      - 신생 출판사 발굴 및 신규 계약
    required:
      - 신입 혹은 콘텐츠관련 영업 경력 1~5년 (도서, 영화, 음악, 게임 등)
      - 리디북스 사용자
      - 적극적이고 원활한 커뮤니케이션 능력
    preferred:
      - 출판사의 영업/마케팅 경력 보유자
      - 장르소설에 대한 애정도가 높은 분
    link: https://ridi.typeform.com/to/OjKvBZ
