department: 사업분석 부문
head: 사업분석 부문
jobs:
  - title: 데이터 애널리스트 (경력)
    description:
      - 리디북스 서점 운영에 필요한 데이터 수집 및 통계 작성
      - 비즈니스 운영을 위한 KPI 작성 및 리포팅 (Excel, Tableau)
      - 운영 및 마케팅 효과 분석을 통한 인사이트 도출
      - 마케팅, 프로모션에 대한 Adhoc 분석
      - 주요 비즈니스적 문제에 대한 원인 분석
    required:
      - 경력 3년 이상
      - SQL 등 기본적인 데이터베이스에 대한 지식 및 리포팅 능력을 가지신 분
      - Excel, SPSS, SAS, R 등 하나 이상의 통계 툴을 이용하여 기술통계 분석이 가능하신 분
      - 데이터마이닝, CRM, 클러스터 분석에 대한 경험을 보유하신 분
    preferred:
      - 통계 혹은 수학, 컴퓨터 전공자
      - 숫자로 이야기하는 것을 좋아하는 분
      - 다양한 사업적인 정보/리서치 능력
      - 온라인 커머스 경력 (쿠팡, 위메프, 신세계, 11번가 등)
      - 콘텐츠 관련 업계 경력 (도서, 영화, 음악, 게임 등)
    link: https://ridi.typeform.com/to/P3rDRk
