department: 운영지원 부문
head: 운영지원 부문
jobs:
  - title: 서점운영 관리 인턴
    description:
      - 리디북스 서점 내 이벤트 실행 계획 수립 및 사이트 운영
      - 서점 운영 시스템 관리 및 운영 정보 입력
      - 운영 프로세스 설계 및 효율화
    required:
      - 온라인 서점 및 서비스 운영에 관심있는 분
      - 책임감 있고 끈기 있는 분
      - 꼼꼼하고 정확한 성향을 가진 분
      - 4년제 졸업 혹은 졸업 예정자 (전공무관)
    preferred:
      - 엑셀 활용 능력 우수자
      - 리디북스 이용자 (리디북스 서점 구조 및 이벤트에 대한 이해도와 관심 높은 분)
      - 유사 직무 경험자 우대
    etc:
      - ※ 인턴 근무(3개월 이하) 종료 후, 평가를 통해 정식 입사 가능
    link: https://ridi.typeform.com/to/Zoq8B8
